name: Simple Deployment to VM

on:
  push:
    branches:
      - main
jobs:
  # This job will deploy our application to a server
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: 'Install'
        run: npm ci
      - name: 'Testing'
        run: npm test
      - name: SSH and deploy to the host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          command_timeout: 200m
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            killall node
            cd githubActionsWorkshop
            git checkout main
            git pull
            npm install 
            npm start &
